name: Test Tool chain installer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  linux-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Building image
        run: docker build -f Test.Dockerfile -t test .
      
      - name: Running Tests
        run: docker run --rm -t test

  
  macos-test:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install packages and creating test script
        run: python3 full_test.py

      - name: Run tests
        shell: bash 
        run: bash test.sh

